// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Check if Supabase is properly configured
export const isSupabaseConfigured = !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY && 
  !SUPABASE_URL.includes('placeholder') && 
  SUPABASE_URL.includes('.supabase.co'));

if (!isSupabaseConfigured) {
  console.warn('⚠️ Supabase is not configured. Auth features will be disabled.');
  console.warn('To enable auth, create a Supabase project and add to .env:');
  console.warn('VITE_SUPABASE_URL=https://your-project.supabase.co');
  console.warn('VITE_SUPABASE_PUBLISHABLE_KEY=your_anon_key');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use fallback values to prevent app crash (auth will fail gracefully)
const url = SUPABASE_URL || 'https://placeholder.supabase.co';
const key = SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYWNlaG9sZGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDk4NzM1MzMsImV4cCI6MTk2NTQ0OTUzM30.placeholder';

export const supabase: SupabaseClient<Database> = createClient<Database>(url, key, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});